set(_CATKIN_CURRENT_PACKAGE "mbot_description")
set(mbot_description_VERSION "1.0.0")
set(mbot_description_MAINTAINER " <TODO@email.com>")
set(mbot_description_PACKAGE_FORMAT "2")
set(mbot_description_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(mbot_description_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(mbot_description_BUILDTOOL_DEPENDS "catkin")
set(mbot_description_BUILDTOOL_EXPORT_DEPENDS )
set(mbot_description_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(mbot_description_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher" "gazebo")
set(mbot_description_TEST_DEPENDS )
set(mbot_description_DOC_DEPENDS )
set(mbot_description_URL_WEBSITE "")
set(mbot_description_URL_BUGTRACKER "")
set(mbot_description_URL_REPOSITORY "")
set(mbot_description_DEPRECATED "")